# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialapp',
            name='trade_type',
            field=models.CharField(blank=True, help_text=b'Be used Weixin', max_length=30, verbose_name=b'trade type'),
        ),
    ]
