# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_socialapp_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialapp',
            name='mch_id',
            field=models.CharField(default='', help_text='MCH ID', max_length=191, verbose_name='MCH ID'),
            preserve_default=False,
        ),
    ]
