# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0005_socialapp_mch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialapp',
            name='mch_appkey',
            field=models.CharField(default='', help_text='MCH App key', max_length=191, verbose_name='MCH App key'),
            preserve_default=False,
        ),
    ]
